branches:
  only:
    - develop

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - git config --global user.name "lyhper"
  - git config --global user.email "lyhper@gmail.com"
  - git clone --branch gh-pages https://github.com/lyhper/vue-ghpages-blog.git dist

install:
  - npm install

script:
  - npm test
  - npm run build

after_script:
  - cd dist
  - echo "lyhper.com" > CNAME
  - cp index.html 404.html
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

env:
  global:
    - GH_REF: github.com/lyhper/vue-ghpages-blog.git
